export const LIST_WORK = 'LIST_WORK';
export const SAVE_LIST_SHOP = 'SAVE_LIST_SHOP';
export const SAVE_TOKEN = 'SAVE_TOKEN';

export const SAVE_LIST_ITEMS = 'SAVE_LIST_ITEMS';
export const SAVE_LIST_SEARCH_ITEMS = 'SAVE_LIST_SEARCH_ITEMS';
export const CHANGE_PRICE_ITEM = 'CHANGE_PRICE_ITEM';


export const SAVE_SHOP_ID_SELECTED = 'SAVE_SHOP_ID_SELECTED';
export const SAVE_ITEM_ID_SELECTED = 'SAVE_ITEM_ID_SELECTED';
